language: ruby

branches:
  only:
  - master

rvm:
  - 2.3.1

before_install:
- openssl aes-256-cbc -K $encrypted_93417c07a8e7_key -iv $encrypted_93417c07a8e7_iv
  -in .deploy_rsa.enc -out .deploy_rsa -d

install:
- gem install nanoc

script:
- nanoc
