sudo: required
language: ruby

branches:
  only:
  - master

rvm:
  - 2.3.1

before_install:
  - openssl aes-256-cbc -K $encrypted_93417c07a8e7_key -iv $encrypted_93417c07a8e7_iv -in .deploy_rsa.enc -out ~/.ssh/id_rsa -d
  - chmod 0600 ~/.ssh/id_rsa
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - sudo apt-get install -y jq
  - sudo apt-add-repository -y ppa:ubuntu-elisp/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y emacs-snapshot
  - gem install nanoc
  # Try to resolve https://travis-ci.org/emacs-china/packages/jobs/190213194#L5352
  - gem install nokogiri

addons:
  ssh_known_hosts: elpa.emacs-china.org

install:
  - emacs --no-site-file --batch -l elpa-packages.el && mv -v *.json content/
  - mkdir -p content/pkgs
  - for i in $( jq 'keys | .[]' -r content/all.json ); do jq ".[\"$i\"]" content/all.json > content/pkgs/$i.json-html; done
  - rsync -zarv --include="*/" --include="*.txt" --exclude="*" elpa-packages@elpa.emacs-china.org:/var/elpa-packages/ tmp
  - for i in tmp/*; do mv $i/* content/pkgs/; done

script:
  - nanoc

after_success:
  - nanoc deploy
